# Generated by Django 4.1.3 on 2023-02-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kakao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, null=True, verbose_name='글 제목')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='글 내용')),
                ('substance', models.TextField(null=True, verbose_name='코멘트')),
                ('write_dttm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='글 작성일')),
                ('board_name', models.CharField(default='주크박스', max_length=32, verbose_name='게시판 종류')),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('files', models.FileField(blank=True, null=True, upload_to='media', verbose_name='파일')),
                ('filename', models.CharField(max_length=100, null=True, verbose_name='파일 이름')),
                ('accept', models.BooleanField(default=False, verbose_name='광고 승인')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=200, null=True, verbose_name='카테고리')),
                ('follow_count', models.PositiveIntegerField(default=0)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislikes', to='kakao.member')),
                ('follow', models.ManyToManyField(blank=True, related_name='follow', to='kakao.member')),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to='kakao.member')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_board', to='kakao.member', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kakao.member')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.PositiveIntegerField(null=True, verbose_name='댓글수')),
            ],
        ),
        migrations.CreateModel(
            name='Report_ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomment_report_user', models.CharField(max_length=200, null=True, verbose_name='신고자')),
                ('recomment_report_date', models.DateTimeField(auto_now_add=True, verbose_name='신고 날짜')),
                ('recomment_report_reason', models.CharField(choices=[('abuse', '욕설'), ('overlap', '도배'), ('ad', '홍보/상업성'), ('lewdness', '음란성'), ('illegal_filming', '불법촬영물'), ('etc', '기다')], max_length=20, null=True, verbose_name='신고 사유')),
                ('recomment_report_detail', models.CharField(max_length=200, null=True, verbose_name='신고 상세내역')),
                ('recomment_report_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.comment', verbose_name='신고 댓글')),
                ('recomment_reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kakao.member', verbose_name='피신고자')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_report_user', models.CharField(max_length=200, null=True, verbose_name='신고자')),
                ('comment_report_date', models.DateTimeField(auto_now_add=True, verbose_name='신고 날짜')),
                ('comment_report_reason', models.CharField(choices=[('abuse', '욕설'), ('overlap', '도배'), ('ad', '홍보/상업성'), ('lewdness', '음란성'), ('illegal_filming', '불법촬영물'), ('etc', '기다')], max_length=20, null=True, verbose_name='신고 사유')),
                ('comment_report_detail', models.CharField(max_length=200, null=True, verbose_name='신고 상세내역')),
                ('comment_report_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.comment', verbose_name='신고 댓글')),
                ('comment_reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kakao.member', verbose_name='피신고자')),
            ],
        ),
        migrations.CreateModel(
            name='Report_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_user', models.CharField(max_length=200, null=True, verbose_name='신고자')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='신고 날짜')),
                ('report_reason', models.CharField(choices=[('abuse', '욕설'), ('overlap', '도배'), ('ad', '홍보/상업성'), ('lewdness', '음란성'), ('illegal_filming', '불법촬영물'), ('etc', '기타')], max_length=20, null=True, verbose_name='신고 사유')),
                ('report_detail', models.CharField(max_length=200, null=True, verbose_name='신고 상세내역')),
                ('report_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='신고 글')),
                ('report_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kakao.member', verbose_name='피신고자')),
            ],
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150, verbose_name='대댓글')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.comment')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kakao.member')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('contents', models.TextField(blank=True, verbose_name='글 내용')),
                ('write_dttm', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakao.member')),
            ],
        ),
        migrations.CreateModel(
            name='Adboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='글 내용')),
                ('write_dttm', models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')),
                ('board_name', models.CharField(default='전광판', max_length=32, verbose_name='게시판 종류')),
                ('images', models.ImageField(upload_to='adver/', verbose_name='광고 사진')),
                ('accept', models.BooleanField(default=False, verbose_name='광고 승인')),
                ('adurl', models.CharField(default='https://www.naver.com', max_length=512, verbose_name='광고url')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_adboard', to='kakao.member', verbose_name='광고 신청자')),
            ],
        ),
    ]
