# Generated by Django 4.1.3 on 2023-02-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='filename',
            field=models.CharField(max_length=600, null=True, verbose_name='파일 이름'),
        ),
    ]
