# Generated by Django 4.1.3 on 2023-02-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='substance',
            field=models.TextField(blank=True, null=True, verbose_name='코멘트'),
        ),
    ]
