# Generated by Django 4.1.3 on 2023-02-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_substance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recom',
            fields=[
                ('user_nickname', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('recom_board1', models.IntegerField()),
                ('recom_board2', models.IntegerField()),
                ('recom_board3', models.IntegerField()),
                ('recom_board4', models.IntegerField()),
                ('recom_board5', models.IntegerField()),
                ('recom_board6', models.IntegerField()),
                ('recom_board7', models.IntegerField()),
                ('recom_board8', models.IntegerField()),
                ('recom_board9', models.IntegerField()),
                ('recom_board10', models.IntegerField()),
                ('recom_board11', models.IntegerField()),
                ('recom_board12', models.IntegerField()),
                ('recom_board13', models.IntegerField()),
                ('recom_board14', models.IntegerField()),
                ('recom_board15', models.IntegerField()),
                ('recom_board16', models.IntegerField()),
                ('recom_board17', models.IntegerField()),
                ('recom_board18', models.IntegerField()),
                ('recom_board19', models.IntegerField()),
                ('recom_board20', models.IntegerField()),
            ],
        ),
    ]
