# Generated by Django 4.1.3 on 2023-02-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('passwd', models.CharField(max_length=50, null=True, verbose_name='비밀번호')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='이메일')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='성별')),
                ('generation', models.CharField(max_length=10, null=True, verbose_name='연령대')),
                ('birth', models.CharField(max_length=50, null=True, verbose_name='생일')),
                ('userimage', models.CharField(blank=True, max_length=4096, null=True, verbose_name='사용자이미지')),
                ('user_total_point', models.PositiveIntegerField(default=0, verbose_name='누적포인트')),
                ('user_current_point', models.PositiveIntegerField(default=0, verbose_name='현재포인트')),
                ('regdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='가입일')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='상세주소')),
                ('social', models.CharField(blank=True, max_length=1, null=True, verbose_name='소셜로그인여부')),
                ('userimg', models.ImageField(blank=True, null=True, upload_to='portimg/', verbose_name='프사')),
            ],
        ),
    ]
