# Generated by Django 4.1.3 on 2023-02-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address2',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True, verbose_name='상세주소'),
        ),
        migrations.AlterField(
            model_name='member',
            name='userimg',
            field=models.ImageField(blank=True, default='Null', null=True, upload_to='portimg/', verbose_name='프사'),
        ),
    ]
