# Generated by Django 4.1.3 on 2023-02-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kakao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.CharField(default='N', max_length=1)),
                ('note_title', models.CharField(default='', max_length=300, verbose_name='쪽지제목')),
                ('note_content', models.TextField(default='', verbose_name='쪽지내용')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='보낸 시간')),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to='kakao.member', verbose_name='받은사람')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to='kakao.member', verbose_name='보낸사람')),
            ],
        ),
    ]
